### PR TITLE
Remove AZ CLI from DockerFile

### PR DESCRIPTION
**Pull request by kenny-chalupa**
This removes the unnecessary az cli install step from the docker file

### CODE REVIEW

**Review by xtophs — CHANGES_REQUESTED** [review]
what about removing `az login` from `./build/entrypoint.sh`?

**Comment by kenny-chalupa** [comment]
> what about removing `az login` from `./build/entrypoint.sh`?

Done

**Comment by kenny-chalupa** [comment]
> what about removing `az login` from `./build/entrypoint.sh`?

I tested this and this worked as well after the changes to the docker file and entry point.sh

**Comment by muradsater** [comment]
> This removes the unnecessary az cli install step from the docker file

This was added to make it possible use "DefaultCredentials" when running the container with a managed identity. Can we authenticate as a managed identity without this?

**Review by xtophs — CHANGES_REQUESTED** [review]
lgtm

**Comment by muradsater** [comment]
> lgtm

@xtophs This was added to make it possible use "DefaultCredentials" when running the container with a managed identity. Can we authenticate as a managed identity without this?

**Comment by nicholasperkins1992** [comment]
> > This removes the unnecessary az cli install step from the docker file
> 
> This was added to make it possible use "DefaultCredentials" when running the container with a managed identity. Can we authenticate as a managed identity without this?

@muradsater Managed identity can still work without default azure creds in the container, when running in azure the service the container is running in AKS or ACI can be configured with managed identity so the container does not have to be

**Review by muradsater — APPROVED** [review]

**Pull request merged**
